### ISSUE TITLE
Unusable in 2019.4.1f1 with HDRP 7.4.2

### ISSUE THREAD

**Issue by vizyviz** [Unity-Technologies/FontainebleauDemo#17]
**Describe the bug**
The project is not compatible with 2019.4.1f1 with HDRP 7.4.2 

**Editor or Runtime**
Editor

**To Reproduce**
1. Install Unity 2019.4.1f1 and HDRP 7.4.2
2. Add project through Unity Hub
3. Allow the Unity upgrade process to run
4. "Fix" the issues in the HDRP window that open.  (Clicked each Fix button individually with 'Create One' selected where offered)
5. Try and open a scene (Used Demo.unity)
5. See error about FountainBleau.asset being corrupt or serialized with a new version of unity.

**Expected behavior**
Scene opens

**Screenshots**
![image](https://user-images.githubusercontent.com/1813301/85430710-5a3c0b00-b535-11ea-81fa-c2d205dde8e2.png)

**Platform**
 - Device:
 - OS: Windows
 - Version: 10

**Comment by Chman** [comment]
Hi,

There isn't any HDRP 7.4.2 version available, only 7.4.1 and 7.5.0. We tried to replicate your issue by following the same steps on both versions as well as with the `7.x.x/release` development branch of HDRP but we're not getting the same issue.

Looking at the error you're getting, either the scene file got corrupted when you pulled the repository or the project was opened with a more recent version of Unity (2020.x alpha/beta) and then re-opened with 2019.4. All the scenes in the Fontainebleau repository are serialized on 2019.3.
