### ISSUE TITLE
error upon rebuilding the lighting

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/FontainebleauDemo#5]
2019.1.4f1
clicking this
![image](https://user-images.githubusercontent.com/26075468/58441584-0e9c0100-8098-11e9-8c7b-24f2ee16db52.png)
then pressing build sunset
![image](https://user-images.githubusercontent.com/26075468/58441590-1bb8f000-8098-11e9-8108-9e8dc1b0c7ec.png)
after 45 minutes of rebaking, errors in the console and no lighting
`Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time
UnityEditor.Experimental.Rendering.ScriptableBakedReflectionSystemWrapper:Internal_ScriptableBakedReflectionSystemWrapper_Tick(SceneStateHash)

`

**Comment by laurenth-personal** [comment]
I don't think we have linked the repository to the tool we use for lightmap baking.
Since we wanted to be able to switch lightmaps at runtime we use a bit of a custom pipeline for baking.
You can check this page for the instructions https://github.com/laurenth-unity/lightmap-switching-tool

**Comment by laurenth-personal** [comment]
I will update the readme file to contain this link

**Comment by laurentopia** [comment]
Gotcha, it switches lightmaps at runtime
