### ISSUE TITLE
Foliage assets render wrong after project import

### ISSUE THREAD

**Issue by laurenth-personal** [Unity-Technologies/FontainebleauDemo#6]
**Describe the bug**
All foliage assets render grey or not at all when importing the project for the first time.

**Expected behavior**
All shading is correct after importing the project for the first time

**Screenshots**
![image](https://user-images.githubusercontent.com/23642191/58974406-9aadd700-87c2-11e9-891e-c9794719912e.png)

**Platform**
All

**Workaround so far**
Locate the sub graph called "foliage shading" in the project, right click on it and reimport it.
This should fix all the foliage assets shading.

**Comment by sebastienlagarde** [comment]
Fixed
