### ISSUE TITLE
2019.1.14f1

### ISSUE THREAD

**Issue by SniperED007** [Unity-Technologies/FontainebleauDemo#7]
Downloaded via GitHub Desktop
Loaded it up in 2019.1.14f1
The Hierarchy window is showing Missing items, missing links between terrain. mesh, prefabs etc, yet they are in the Project.

**Comment by sebastienlagarde** [comment]
Hi, we have update the project for latest 2019.3 and 7.2.0. As it is the first official out fo preview we will not support the previous release. Sorry.
